### ISSUE TITLE
Correct error when SIM card is missing

### ISSUE THREAD

**Issue by whitipet** [KieronQuinn/SIMNumberSetter#10]
If the seven card is not inserted in the phone, it shows the error "Failed to connect to the Xposed service, make sure the module is enabled and you have rebooted", but this is not a correct error, confusing.
I tried to flash some old phones and install xposed in different ways, but I kept getting this error. But when I just inserted the SIM card, everything worked.
Judging by [this code](https://github.com/KieronQuinn/SIMNumberSetter/blob/ea77f03e3d06fd12d19cdde43dac11abb8020a41/app/src/main/java/com/kieronquinn/app/simnumbersetter/ui/screens/main/MainViewModel.kt#L111), only the presence of the number is checked, and when it is missing, the general xposed error is displayed. I suggest adding an additional check for the presence of a SIM card.

**Comment by KieronQuinn** [comment]
You're right in that the Xposed error is displayed when it shouldn't be, I'm aware of that I just need to get around to fixing it. There's no need for a SIM presence check though, as I can simply differentiate between `runWithService` returning null and the exception (the former is Xposed failing, the latter is an incompatible card)
