### ISSUE TITLE
Not detecting lsposed

### ISSUE THREAD

**Issue by AkshiTChauhan-max** [KieronQuinn/SIMNumberSetter#11]
![Screenshot_20220306-210924_Pixel_Launcher](https://user-images.githubusercontent.com/65775754/156930368-28761543-8091-41c8-b954-e30246254ad6.png)
![Screenshot_20220306-210739_Pixel_Launcher](https://user-images.githubusercontent.com/65775754/156930371-8a9c12c4-8190-474b-8806-2531fd09d234.png)

> 
[LSPosed_2022-03-06T21_09_14.625.zip](https://github.com/KieronQuinn/SIMNumberSetter/files/8192916/LSPosed_2022-03-06T21_09_14.625.zip)
 Not working in pixel extended Android 11 rom

**Comment by KieronQuinn** [comment]
Caused by #10
