### ISSUE TITLE
Esim

### ISSUE THREAD

**Issue by Harshan-Dinuka-Gunarathne** [KieronQuinn/SIMNumberSetter#15]
How is the comparability with e-sims? My esim does not have my own phone number saved to it. So phone shows it as an unknown number... Can I use this app to fix it ?

**Comment by KieronQuinn** [comment]
You can try, no idea if it would work. Do let me know if it does!

**Comment by Harshan-Dinuka-Gunarathne** [comment]
Actually it worked without any issues :). I added my phone number to sim so my phone no longer shows my phone number as unknown
