### ISSUE TITLE
[Feature Request] Support for eSIM on Google Pixel 7Pro

### ISSUE THREAD

**Issue by huajijam** [KieronQuinn/SIMNumberSetter#17]
some carrier's eSIM will leave sim's CARRIER,UICC,IMS all bank and not set,and some apps will have a problem with it

**Comment by huajijam** [comment]
my device is pixel 7 pro,and I can't find my eSim to set,It always reading my sim card even I disable it  
should I remove the card?

**Comment by huajijam** [comment]
ok,I fix it, I need to enable 2 esim,unplug physical sim card to set,
If not, I will keep getting error for Failed to connect to the Xposed service

**Comment by huajijam** [comment]
I think setting phone number in eSIM will be confusing if there are two eSIM and they have no phone number
The number has been set to the non sms/data one,no idea why
I think there should be a carrier info or something to make sure which is which.

**Comment by huajijam** [comment]
I am checking in with *#*#4636*#*#*
the first Esim to be activated will be phone1...., which may explain why it cannot be set in only one card

**Comment by KieronQuinn** [comment]
Yes, the SIM has to be in slot 1. That goes for both physical and eSIM, it's down to restrictions of the OS (there's no way to apply it to the second slot)
