### ISSUE TITLE
小米手机miui12.5无法使用？

### ISSUE THREAD

**Issue by jaydon-zhuang** [KieronQuinn/SIMNumberSetter#2]
小米10pro， miui12.5 安卓11，magisk ＋ lsp，打开APP显示“无法连接xposed服务…”是不是不支持lsp框架啊？谢谢
![Screenshot_2022-02-11-22-27-07-569_com android shell](https://user-images.githubusercontent.com/85752999/153610825-c0ae9292-547d-45aa-8c75-422c6d3d262a.jpg)
![Screenshot_2022-02-11-22-16-51-950_com android shell](https://user-images.githubusercontent.com/85752999/153610824-6440e6d0-f826-449d-97aa-e41e948405ac.jpg)
![Screenshot_2022-02-11-22-16-46-795_com kieronquinn app simnumbersetter](https://user-images.githubusercontent.com/85752999/153610837-e05e944c-80fd-4414-8f94-1d09096eb7b2.jpg)

**Comment by KieronQuinn** [comment]
MIUI isn't something I support, as they change far too much in the OS.

**Comment by jaydon-zhuang** [comment]
> 

请发你的银行卡号给我，我打钱给你，你修复他。😘
