### ISSUE TITLE
lsposed and Android13 support 

### ISSUE THREAD

**Issue by 20171213** [KieronQuinn/SIMNumberSetter#20]
please![Screenshot_20230731-230130_SIM 号码设置.png](https://github.com/KieronQuinn/SIMNumberSetter/assets/34502902/f6d259f7-b67e-4cbd-b04f-b5052f4deef0)

**Comment by KieronQuinn** [comment]
The app already supports Android 13 and Lsposed. Your error is due to non-standard changes by the OEM. This module does not support those.

**Comment by 20171213** [comment]
I found the problem，When the phone number is changed to unknown, the module cannot be activated on another phone
