### ISSUE TITLE
Failed to connect to Xposed service

### ISSUE THREAD

**Issue by CodexUnico** [KieronQuinn/SIMNumberSetter#22]
Unfortunately it is not working for me.

I have magisk 25+

And latest Lsposed (1.9.2) 

Have also enabled the module in Lsposed, and granted root access, and rebooted multiple times.

But unfortunately it still throws the error "Failed to connect to Xposed service....."

![Screenshot_2023-12-07-03-12-07-088_com kieronquinn app simnumbersetter](https://github.com/KieronQuinn/SIMNumberSetter/assets/137084283/9a1569a8-6bb5-4a79-9674-67ed0e802f65)

**Comment by KieronQuinn** [comment]
#3

**Comment by CodexUnico** [comment]
Now I think that MiUi devices with mediatek chips aren't working.
