### ISSUE TITLE
Problem with Lsposed

### ISSUE THREAD

**Issue by angeluskun** [KieronQuinn/SIMNumberSetter#3]
I installed Lsposed zygisk versión and enabled the module from there AND grated root permission then reboot and the app dosent detect Lsposed and force me to close it

**Comment by KieronQuinn** [comment]
What device and firmware?

**Comment by angeluskun** [comment]
Poco x3 pro android 12 CRdroid

**Comment by KieronQuinn** [comment]
Ok, it should work on that. Please post your LSposed logs.

**Comment by angeluskun** [comment]
- 
[LSPosed_2022-02-11T21_50_22.518.zip](https://github.com/KieronQuinn/SIMNumberSetter/files/8052660/LSPosed_2022-02-11T21_50_22.518.zip)
[ ]

**Comment by KieronQuinn** [comment]
There's no error in there. Could you send a screenshot of the LSposed page for Sim Number Changer, showing the enabled apps?

**Comment by angeluskun** [comment]
> There's no error in there. Could you send a screenshot of the LSposed page for Sim Number Changer, showing the enabled apps?

Sure :)

**Comment by angeluskun** [comment]
![Screenshot_20220212-124227_LSPosed](https://user-images.githubusercontent.com/23154910/153724084-9a60e13a-68f2-4dd0-a6d4-a44e6ac4f8fa.png)

**Comment by KieronQuinn** [comment]
Yeah that should work, I have no idea why it's not doing, sorry.

**Comment by angeluskun** [comment]
> Yeah that should work, I have no idea why it's not doing, sorry.

Dont worry thanks for trying (8

**Comment by erayrafet** [comment]
I just wanted to add that I get the same error with the app using LSPosed and Magisk 24 on my POCOPHONE F1 AwakenOS Android 12. Probably something to do with Xiaomi.

**Comment by Ante0** [comment]
Same on OnePlus 8 Pro, Magisk 24, OOS11

**Comment by MMETMA** [comment]
If you're using shamiko module remove it. It's messing with root privileges and lsposed's too

**Comment by ghost** [comment]
Same here on realme 1 ricedroid 4.5 Android 12.1

**Comment by Beat-YT** [comment]
Install the riru flavor module as well as the riru version of LSPosed. This worked for me

**Comment by megapro17** [comment]
This shit doesn't work at all. Tried with zygisk lsposed, with riru, blacklist is disabled and is still doesn't connect! Magisk and lsposed are working completely fine. Android 13 MIUI 14 Mi 11

**Comment by KieronQuinn** [comment]
> This shit doesn't work at all. Tried with zygisk lsposed, with riru, blacklist is disabled and is still doesn't connect! Magisk and lsposed are working completely fine. Android 13 MIUI 14 Mi 11

https://github.com/KieronQuinn/SIMNumberSetter/issues/2#issuecomment-1036276303

It works for everyone else. Blame MIUI.

**Comment by megapro17** [comment]
Angeluskun has not been able to get it to work on an AOSP-based FW either, as well as many other users that are not using MIUI. 
> Poco x3 pro android 12 CRdroid
> Same here on realme 1 ricedroid 4.5 Android 12.1
> Same on OnePlus 8 Pro, Magisk 24, OOS11
> LSPosed and Magisk 24 on my POCOPHONE F1 AwakenOS Android 12

**Comment by KieronQuinn** [comment]
> Angeluskun has not been able to get it to work on an AOSP-based FW either, as well as many other users that are not using MIUI.
> 
> > Poco x3 pro android 12 CRdroid
> > Same here on realme 1 ricedroid 4.5 Android 12.1
> > Same on OnePlus 8 Pro, Magisk 24, OOS11
> > LSPosed and Magisk 24 on my POCOPHONE F1 AwakenOS Android 12

It's still a MIUI-origin device. I can't guarantee support on devices where the proprietary blobs are fucked with by Xiaomi. 

Some see success with different LSPosed builds or by disabling other mods. Other devices are known to work. This is not something I can fix.

**Comment by megapro17** [comment]
If you can't fix it, then i'll do it myself. 
And I found a reason. 
It doesn't work because it fails at getting line1Number, which is not even needed, for changing this value. If i remove this line, i can sucessfuly change a number, and see it on other phone. That function is also deprecated https://developer.android.com/reference/android/telephony/TelephonyManager#getLine1Number()

<img src="https://user-images.githubusercontent.com/16743370/227321143-ed9c714a-7d02-4f57-a0ce-e28a8d4216b2.png" height="280">

<img src="https://user-images.githubusercontent.com/16743370/227321720-791db89f-a9ef-461f-a1e0-c9332b4b0a3c.jpg" height="280">
<img src="https://user-images.githubusercontent.com/16743370/227321732-13eac840-b48e-4f2c-8426-5c2e299bd2f8.jpg" height="280">
<img src="https://user-images.githubusercontent.com/16743370/227321746-260cec03-cb7b-46eb-8eab-31926cfdb0c6.png" height="280">

Fucked up blobs yeah whatever

**Comment by KieronQuinn** [comment]
You're looking at the wrong class. It's not deprecated at all:

https://cs.android.com/android/platform/superproject/+/refs/heads/master:frameworks/opt/telephony/src/java/com/android/internal/telephony/PhoneInternalInterface.java;drc=5f971bfb26b0f0cf4ddca5da71e89a2690cba919;l=698

If OEMs mess with internal classes, how the hell am I supposed to support them without having every device available? I'm not crippling the app for them - the current number IS used, it's shown to the user to confirm the current number and that the change worked!

**Comment by megapro17** [comment]
well, i can agree that miui is not the best made firmware. I was just angry because the app was showing an error related to xposed, when it was something else entirely. Next time, it is better to describe each step in detail so that you understand the problem clearly.

**Comment by KieronQuinn** [comment]
That is what #10 is for.

**Comment by megapro17** [comment]
aren't you going to add some workaround if get sim number is not working?

**Comment by maulana-kurniawan** [comment]
> If you can't fix it, then i'll do it myself.

Hei @megapro17 can i got your modified module app? I have a same problem with current SIM Number Setter app on MIUI 13.

**Comment by megapro17** [comment]
If you change a number in the MIUI settings, it's not written to the SIM card, it's only cached in the system. If you set an empty field, it will delete this cached value. So before you make a change you need to clear a field. Go to settings - sim - sim 1 number and set a blank field. Then eject and insert a card, change a number in the application, reeject again and look in settings, it should show a number that is stored in sim.

I will make a better version soon.
[base.zip](https://github.com/KieronQuinn/SIMNumberSetter/files/11220225/base.zip)

**Comment by maulana-kurniawan** [comment]
@megapro17 thanks a lot! Really appreciated it!

**Comment by CodexUnico** [comment]
> If you change a number in the MIUI settings, it's not written to the SIM card, it's only cached in the system. If you set an empty field, it will delete this cached value. So before you make a change you need to clear a field. Go to settings - sim - sim 1 number and set a blank field. Then eject and insert a card, change a number in the application, reeject again and look in settings, it should show a number that is stored in sim.
> 
> I will make a better version soon. [base.zip](https://github.com/KieronQuinn/SIMNumberSetter/files/11220225/base.zip)



Could it be that devices with mediatek chips cause issues??

And the app you provided (base.apk) is not even getting installed on my device.

**Comment by babyharpsea** [comment]
It's not just Xiaomi, same issue over here, everything is correct, yet it isn't connecting to LSPosed. I have a Samsung a52s

**Comment by anyuta1166** [comment]
> If you can't fix it, then i'll do it myself. And I found a reason. It doesn't work because it fails at getting line1Number, which is not even needed, for changing this value. If i remove this line, i can sucessfuly change a number, and see it on other phone.

@megapro17 Thanks for your suggestion. I've slightly modified it, and the module works like a charm after modification.

Actually you don't need to comment out the whole getting line1Number stuff.

The issue is that in newer Android versions, you can't get line1Number if it is unset. But you can successfully get it if it is set to any number.

So a small modification makes the module work again:

https://github.com/anyuta1166/SIMNumberSetter/commit/dcdb26ffcd526d540d9f5ae01f0eedee6eceef35

**Comment by noname29** [comment]
says package appears to be invalid android 12 samsung @megapro17 

do you have modified base.apk ?

**Comment by maulana-kurniawan** [comment]
@noname29 just install the apk provided by megapro17 with this adb command:
`adb install -t base.apk`
