### ISSUE TITLE
1 bug and 1 suggestion

### ISSUE THREAD

**Issue by MMETMA** [KieronQuinn/SIMNumberSetter#5]
**The BUG** : 
I have 2 sim cards (Etisalat Egypt & Vodafone Egypt) the first one has a phone number and i can change it just fine, But when i try to change the 2nd sim number (which is unknown by default) it just won't get changed it says saving but it doesn't.

**The Suggestion** : 
Add the ability to choose which sim to do changes to

**Comment by KieronQuinn** [comment]
#1

**Comment by MMETMA** [comment]
Sorry i didn't see the closed issue
