### ISSUE TITLE
New gen of cards

### ISSUE THREAD

**Issue by BlueMan1986** [KieronQuinn/SIMNumberSetter#9]
I have same operator sim cards, one is little older, one is new, they are both 4G cards... On older it saves, on new one it does not... I pictured you a sim, maybe you can recognize and know what you need to update if it possible... On picture, top one is working one (older type 4G card) and on bottom is "new" one that is not saving info (it is also 4G) Both are same operator "mt:s" Telekom Srbija. (Serbian mobile operator).
https://ibb.co/b6yVyJD

**Comment by KieronQuinn** [comment]
Unfortunately as the platform is doing the actual writing, there's nothing I can do to fix that, sorry.
